#!/usr/bin/env sh

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#       not find so, but you have some other *nix shell, you may want to try it.
#
#   (2) Upstream projects may declare new dependencies; this script
#       will need to be updated when the dependencies change.
#
#   (3) This script is generated each time Gradle is run.
#
#   (4) You can more easily run the build if you remove
#       this script, so you can use just 'gradle' like normal.
#
#   For more details, see the full license text in the LICENSE file
#
##############################################################################

##############################################################################
#
#   Gradle startup script for UN*X
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
PRG="$0"
# Need this for relative symlinks.
while [ -h "$PRG" ] ; do
    ls -ld "$PRG"
    LINK=$(ls -ld "$PRG" | awk '{print $NF}')
    case $LINK in
        /*) PRG="$LINK" ;;
        *) PRG=$(dirname "$PRG")"/$LINK" ;;
    esac
done
SAVED="$(cd "$(dirname \"$PRG\")" && pwd)"
cd "$SAVED" > /dev/null
APP_HOME=$(pwd -P)
cd "$ODIR" 2>/dev/null || exit 1

APP_NAME="Gradle"
APP_BASE_NAME=$(basename "$0")
export APP_BASE_NAME

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='" -Xmx64m -Xms64m "'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$(uname)" in
  CYGWIN* )
    cygwin=true
    ;;
  Darwin* )
    darwin=true
    ;;
  MSYS* | MINGW* )
    msys=true
    ;;
  NONSTOP* )
    nonstop=true
    ;;
esac

export CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $- in
      *i*) ;;
      *) set +m ;;
    esac
    dlimit=$(ulimit -S -n)
    if [ $? -eq 0 ] ; then
        if [ "$dlimit" != 'unlimited' ] ; then
            if [ $dlimit -lt 4096 ] ; then
                ulimit -S -n 4096
            fi
        fi
    fi
fi

if $cygwin ; then
    APP_HOME=$(cygpath --path --mixed "$APP_HOME")
    CLASSPATH=$(cygpath --path --mixed "$CLASSPATH")

    JAVACMD=$(cygpath --unix "$JAVACMD")

    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg do
        if expr "$arg" : '[^=]*=' > /dev/null ; then
            eval export arg
        else
            arg=$(echo "$arg" | sed "s/'/'\\\\''/g")
            eval "args=\"$args '$arg'\"" 2>/dev/null
        fi
    done
    set -- $args
fi

if $msys ; then
    arg_begin=$(( ${#} + 1 ))
    for arg in "$@" ; do
        arg_count=$((
            $arg_count + 1
        ))
        APP_ARGS[ $arg_count ]="$arg"
    done
fi

# Collect all arguments for the java command, stacking in reverse order:
for arg in "$@" ; do
    if expr "$arg" : '[^=]*=' > /dev/null ; then
        eval export "$arg"
    else
        eval "args=\"$arg '$args'\"" 2>/dev/null
    fi
done

eval set -- $args

exec "$JAVACMD" "$@"
